### ISSUE TITLE
Sorting is not done correctly

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Sorting#13]
When you try to sort a CSS file, the ***** is not properly sorted. Meaning the outcome is
```css
*
}

  box-sizing: border-box;
}
```
and should be 
```css
* {
  box-sizing: border-box;
}
```
